version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
